In [429]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [430]:
df = pd.read_excel(r'C:/Users/shari/Downloads/DataScience Bootcamp/Python/FeatureEngineering/flight_price.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [431]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [432]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [433]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [434]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [435]:
# working on Date of Journey

df['Date'] = df['Date_of_Journey'].str.split("/").str[0].astype(int)
df['Month'] = df['Date_of_Journey'].str.split("/").str[1].astype(int)
df['Year'] = df['Date_of_Journey'].str.split("/").str[2].astype(int)

In [436]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [437]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), str(10)
memory usage: 1.1 MB

In [438]:
df.drop('Date_of_Journey', axis=1, inplace=True)

In [439]:
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [440]:
df.drop('Route', axis=1, inplace=True)

In [441]:
df

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [442]:
# Working on Arrival Time

df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x: x.split(' ')[0])
df

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,09:25,04:25,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [443]:
df['Arrival_Hours'] = df['Arrival_Time'].str.split(':').str[0].astype(int)
df['Arrival_Mins'] = df['Arrival_Time'].str.split(':').str[1].astype(int)

df

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins
0,IndiGo,Banglore,New Delhi,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,09:25,04:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019,22,25
10679,Air India,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019,23,20
10680,Jet Airways,Banglore,Delhi,08:20,11:20,3h,non-stop,No info,7229,27,4,2019,11,20
10681,Vistara,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019,14,10
10682,Air India,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019,19,15

In [444]:
df.drop('Arrival_Time', axis=1, inplace=True)

In [445]:
df

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,19:55,2h 30m,non-stop,No info,4107,9,4,2019,22,25
10679,Air India,Kolkata,Banglore,20:45,2h 35m,non-stop,No info,4145,27,4,2019,23,20
10680,Jet Airways,Banglore,Delhi,08:20,3h,non-stop,No info,7229,27,4,2019,11,20
10681,Vistara,Banglore,New Delhi,11:30,2h 40m,non-stop,No info,12648,1,3,2019,14,10
10682,Air India,Delhi,Cochin,10:55,8h 20m,2 stops,No info,11753,9,5,2019,19,15

In [446]:
df['Departure_Hours'] = df['Dep_Time'].str.split(':').str[0].astype(int)
df['Departure_Mins'] = df['Dep_Time'].str.split(':').str[1].astype(int)

In [447]:
df.head()

,Airline,Source,Destination,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins
0,IndiGo,Banglore,New Delhi,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,09:25,19h,2 stops,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [448]:
df.drop('Dep_Time', axis=1, inplace=True)

In [449]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2 stops,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [450]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Duration         10683 non-null  str
 4   Total_Stops      10682 non-null  str
 5   Additional_Info  10683 non-null  str
 6   Price            10683 non-null  int64
 7   Date             10683 non-null  int64
 8   Month            10683 non-null  int64
 9   Year             10683 non-null  int64
 10  Arrival_Hours    10683 non-null  int64
 11  Arrival_Mins     10683 non-null  int64
 12  Departure_Hours  10683 non-null  int64
 13  Departure_Mins   10683 non-null  int64
dtypes: int64(8), str(6)
memory usage: 1.1 MB

In [451]:
df.isnull().sum()

Airline            0
Source             0
Destination        0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
Date               0
Month              0
Year               0
Arrival_Hours      0
Arrival_Mins       0
Departure_Hours    0
Departure_Mins     0
dtype: int64

In [452]:
df['Duration_Hours'] = df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['Duration_Mins'] = df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [453]:
df.drop('Duration', axis=1, inplace=True)

In [454]:
df.head(2)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,5,2019,13,15,5,50,7,25

In [455]:
df['Duration_Hours'] = df['Duration_Hours'].str.replace('m', '')

In [456]:
df["Duration_Hours"] = df["Duration_Hours"].astype(int)

In [457]:
df['Duration_Mins'].unique()

array(['50', '25', nan, '45', '30', '5', '15', '35', '10', '20', '55',
       '40'], dtype=object)

In [458]:
df['Duration_Mins']=df['Duration_Mins'].fillna(0)

In [459]:
df['Duration_Mins']=df['Duration_Mins'].astype(int)

In [460]:
df

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2 stops,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,1 stop,No info,6218,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,1 stop,No info,13302,1,3,2019,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,non-stop,No info,4107,9,4,2019,22,25,19,55,2,30
10679,Air India,Kolkata,Banglore,non-stop,No info,4145,27,4,2019,23,20,20,45,2,35
10680,Jet Airways,Banglore,Delhi,non-stop,No info,7229,27,4,2019,11,20,8,20,3,0
10681,Vistara,Banglore,New Delhi,non-stop,No info,12648,1,3,2019,14,10,11,30,2,40
10682,Air India,Delhi,Cochin,2 stops,No info,11753,9,5,2019,19,15,10,55,8,20

In [461]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Total_Stops      10682 non-null  str
 4   Additional_Info  10683 non-null  str
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_Hours    10683 non-null  int64
 10  Arrival_Mins     10683 non-null  int64
 11  Departure_Hours  10683 non-null  int64
 12  Departure_Mins   10683 non-null  int64
 13  Duration_Hours   10683 non-null  int64
 14  Duration_Mins    10683 non-null  int64
dtypes: int64(10), str(5)
memory usage: 1.2 MB

In [462]:
df.head(2)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,5,2019,13,15,5,50,7,25

In [463]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Total_Stops      10682 non-null  str
 4   Additional_Info  10683 non-null  str
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_Hours    10683 non-null  int64
 10  Arrival_Mins     10683 non-null  int64
 11  Departure_Hours  10683 non-null  int64
 12  Departure_Mins   10683 non-null  int64
 13  Duration_Hours   10683 non-null  int64
 14  Duration_Mins    10683 non-null  int64
dtypes: int64(10), str(5)
memory usage: 1.2 MB

In [464]:
df.isnull().sum()

Airline            0
Source             0
Destination        0
Total_Stops        1
Additional_Info    0
Price              0
Date               0
Month              0
Year               0
Arrival_Hours      0
Arrival_Mins       0
Departure_Hours    0
Departure_Mins     0
Duration_Hours     0
Duration_Mins      0
dtype: int64

In [465]:
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins
9039,Air India,Delhi,Cochin,NaN,No info,7480,6,5,2019,9,25,9,45,23,40

In [466]:
stops_mode = df[df['Total_Stops'].notna()]['Total_Stops'].mode()[0]
stops_mode

'1 stop'

In [467]:
df['Total_Stops'] = df['Total_Stops'].fillna(stops_mode)

In [468]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_Hours, Arrival_Mins, Departure_Hours, Departure_Mins, Duration_Hours, Duration_Mins]
Index: []

In [469]:
df

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2 stops,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,1 stop,No info,6218,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,1 stop,No info,13302,1,3,2019,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,non-stop,No info,4107,9,4,2019,22,25,19,55,2,30
10679,Air India,Kolkata,Banglore,non-stop,No info,4145,27,4,2019,23,20,20,45,2,35
10680,Jet Airways,Banglore,Delhi,non-stop,No info,7229,27,4,2019,11,20,8,20,3,0
10681,Vistara,Banglore,New Delhi,non-stop,No info,12648,1,3,2019,14,10,11,30,2,40
10682,Air India,Delhi,Cochin,2 stops,No info,11753,9,5,2019,19,15,10,55,8,20

In [470]:
df.isnull().sum()

Airline            0
Source             0
Destination        0
Total_Stops        0
Additional_Info    0
Price              0
Date               0
Month              0
Year               0
Arrival_Hours      0
Arrival_Mins       0
Departure_Hours    0
Departure_Mins     0
Duration_Hours     0
Duration_Mins      0
dtype: int64

In [471]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Total_Stops      10683 non-null  str
 4   Additional_Info  10683 non-null  str
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_Hours    10683 non-null  int64
 10  Arrival_Mins     10683 non-null  int64
 11  Departure_Hours  10683 non-null  int64
 12  Departure_Mins   10683 non-null  int64
 13  Duration_Hours   10683 non-null  int64
 14  Duration_Mins    10683 non-null  int64
dtypes: int64(10), str(5)
memory usage: 1.2 MB

In [472]:
# Ordinal Encoding for the column -- Total Stops

df.head(2)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,5,2019,13,15,5,50,7,25

In [473]:
df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', '4 stops']
Length: 5, dtype: str

In [474]:
from sklearn.preprocessing import OrdinalEncoder

# Instance creation
oe = OrdinalEncoder(categories=[['non-stop','1 stop','2 stops','3 stops','4 stops']])

# fit and transform
oe_enc = oe.fit_transform(df[['Total_Stops']])
oe_enc

array([[0.],
       [2.],
       [2.],
       ...,
       [0.],
       [0.],
       [2.]], shape=(10683, 1))

In [475]:
# converting into a dataframe

df_encoded = pd.DataFrame(data=oe_enc, columns=['Stops'])
df_encoded

       Stops
0        0.0
1        2.0
2        2.0
3        1.0
4        1.0
...      ...
10678    0.0
10679    0.0
10680    0.0
10681    0.0
10682    2.0

[10683 rows x 1 columns]

In [476]:
# concatination

df = pd.concat([df,df_encoded], axis=1)

In [477]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info',
       'Price', 'Date', 'Month', 'Year', 'Arrival_Hours', 'Arrival_Mins',
       'Departure_Hours', 'Departure_Mins', 'Duration_Hours', 'Duration_Mins',
       'Stops'],
      dtype='str')

In [478]:
df.columns.value_counts()

Airline            1
Source             1
Destination        1
Total_Stops        1
Additional_Info    1
Price              1
Date               1
Month              1
Year               1
Arrival_Hours      1
Arrival_Mins       1
Departure_Hours    1
Departure_Mins     1
Duration_Hours     1
Duration_Mins      1
Stops              1
Name: count, dtype: int64

In [479]:
# df.drop(df.columns[3], axis=1, inplace=True)

In [480]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Total_Stops      10683 non-null  str
 4   Additional_Info  10683 non-null  str
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_Hours    10683 non-null  int64
 10  Arrival_Mins     10683 non-null  int64
 11  Departure_Hours  10683 non-null  int64
 12  Departure_Mins   10683 non-null  int64
 13  Duration_Hours   10683 non-null  int64
 14  Duration_Mins    10683 non-null  int64
 15  Stops            10683 non-null  float64
dtypes: float64(1), int64(10), str(5)
memory usage: 1.3 MB

In [481]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins,Stops
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,3,2019,1,10,22,20,2,50,0.0
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,5,2019,13,15,5,50,7,25,2.0
2,Jet Airways,Delhi,Cochin,2 stops,No info,13882,9,6,2019,4,25,9,25,19,0,2.0
3,IndiGo,Kolkata,Banglore,1 stop,No info,6218,12,5,2019,23,30,18,5,5,25,1.0
4,IndiGo,Banglore,New Delhi,1 stop,No info,13302,1,3,2019,21,35,16,50,4,45,1.0

In [482]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Total_Stops      10683 non-null  str
 4   Additional_Info  10683 non-null  str
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_Hours    10683 non-null  int64
 10  Arrival_Mins     10683 non-null  int64
 11  Departure_Hours  10683 non-null  int64
 12  Departure_Mins   10683 non-null  int64
 13  Duration_Hours   10683 non-null  int64
 14  Duration_Mins    10683 non-null  int64
 15  Stops            10683 non-null  float64
dtypes: float64(1), int64(10), str(5)
memory usage: 1.3 MB

In [483]:
df

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins,Stops
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,3,2019,1,10,22,20,2,50,0.0
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,5,2019,13,15,5,50,7,25,2.0
2,Jet Airways,Delhi,Cochin,2 stops,No info,13882,9,6,2019,4,25,9,25,19,0,2.0
3,IndiGo,Kolkata,Banglore,1 stop,No info,6218,12,5,2019,23,30,18,5,5,25,1.0
4,IndiGo,Banglore,New Delhi,1 stop,No info,13302,1,3,2019,21,35,16,50,4,45,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,non-stop,No info,4107,9,4,2019,22,25,19,55,2,30,0.0
10679,Air India,Kolkata,Banglore,non-stop,No info,4145,27,4,2019,23,20,20,45,2,35,0.0
10680,Jet Airways,Banglore,Delhi,non-stop,No info,7229,27,4,2019,11,20,8,20,3,0,0.0
10681,Vistara,Banglore,New Delhi,non-stop,No info,12648,1,3,2019,14,10,11,30,2,40,0.0
10682,Air India,Delhi,Cochin,2 stops,No info,11753,9,5,2019,19,15,10,55,8,20,2.0

In [484]:
df['Total_Stops']

0        non-stop
1         2 stops
2         2 stops
3          1 stop
4          1 stop
           ...
10678    non-stop
10679    non-stop
10680    non-stop
10681    non-stop
10682     2 stops
Name: Total_Stops, Length: 10683, dtype: str

In [485]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info',
       'Price', 'Date', 'Month', 'Year', 'Arrival_Hours', 'Arrival_Mins',
       'Departure_Hours', 'Departure_Mins', 'Duration_Hours', 'Duration_Mins',
       'Stops'],
      dtype='str')

In [486]:
df.drop('Total_Stops', axis=1, inplace=True)

In [487]:
df

,Airline,Source,Destination,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins,Stops
0,IndiGo,Banglore,New Delhi,No info,3897,24,3,2019,1,10,22,20,2,50,0.0
1,Air India,Kolkata,Banglore,No info,7662,1,5,2019,13,15,5,50,7,25,2.0
2,Jet Airways,Delhi,Cochin,No info,13882,9,6,2019,4,25,9,25,19,0,2.0
3,IndiGo,Kolkata,Banglore,No info,6218,12,5,2019,23,30,18,5,5,25,1.0
4,IndiGo,Banglore,New Delhi,No info,13302,1,3,2019,21,35,16,50,4,45,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,No info,4107,9,4,2019,22,25,19,55,2,30,0.0
10679,Air India,Kolkata,Banglore,No info,4145,27,4,2019,23,20,20,45,2,35,0.0
10680,Jet Airways,Banglore,Delhi,No info,7229,27,4,2019,11,20,8,20,3,0,0.0
10681,Vistara,Banglore,New Delhi,No info,12648,1,3,2019,14,10,11,30,2,40,0.0
10682,Air India,Delhi,Cochin,No info,11753,9,5,2019,19,15,10,55,8,20,2.0

In [492]:
# One hot Encoding for Columns Airline, Source, Destination and Additional_Info

from sklearn.preprocessing import OneHotEncoder

#instance
ohe=OneHotEncoder()

#fit and transform
enc = ohe.fit_transform(df[['Airline', 'Source', 'Destination', 'Additional_Info']]).toarray()

In [494]:
# Converting to a dataframe

df_ohe = pd.DataFrame(data=enc, columns=ohe.get_feature_names_out())
df_ohe

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10679,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10682,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [496]:
# concatination

df = pd.concat([df, df_ohe], axis=1)

In [497]:
df.head(2)

,Airline,Source,Destination,Additional_Info,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,IndiGo,Banglore,New Delhi,No info,3897,24,3,2019,1,10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,Air India,Kolkata,Banglore,No info,7662,1,5,2019,13,15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [498]:
df.drop(['Airline','Source','Destination','Additional_Info'], axis=1, inplace=True)

In [499]:
df

,Price,Date,Month,Year,Arrival_Hours,Arrival_Mins,Departure_Hours,Departure_Mins,Duration_Hours,Duration_Mins,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,3897,24,3,2019,1,10,22,20,2,50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,7662,1,5,2019,13,15,5,50,7,25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,13882,9,6,2019,4,25,9,25,19,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,6218,12,5,2019,23,30,18,5,5,25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,13302,1,3,2019,21,35,16,50,4,45,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,4107,9,4,2019,22,25,19,55,2,30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10679,4145,27,4,2019,23,20,20,45,2,35,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,7229,27,4,2019,11,20,8,20,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,12648,1,3,2019,14,10,11,30,2,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10682,11753,9,5,2019,19,15,10,55,8,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [500]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 44 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Price                                         10683 non-null  int64
 1   Date                                          10683 non-null  int64
 2   Month                                         10683 non-null  int64
 3   Year                                          10683 non-null  int64
 4   Arrival_Hours                                 10683 non-null  int64
 5   Arrival_Mins                                  10683 non-null  int64
 6   Departure_Hours                               10683 non-null  int64
 7   Departure_Mins                                10683 non-null  int64
 8   Duration_Hours                                10683 non-null  int64
 9   Duration_Mins                                 10683 non-null  int64
 10  Stops                                         10683 non-null  float64
 11  Airline_Air Asia                              10683 non-null  float64
 12  Airline_Air India                             10683 non-null  float64
 13  Airline_GoAir                                 10683 non-null  float64
 14  Airline_IndiGo                                10683 non-null  float64
 15  Airline_Jet Airways                           10683 non-null  float64
 16  Airline_Jet Airways Business                  10683 non-null  float64
 17  Airline_Multiple carriers                     10683 non-null  float64
 18  Airline_Multiple carriers Premium economy     10683 non-null  float64
 19  Airline_SpiceJet                              10683 non-null  float64
 20  Airline_Trujet                                10683 non-null  float64
 21  Airline_Vistara                               10683 non-null  float64
 22  Airline_Vistara Premium economy               10683 non-null  float64
 23  Source_Banglore                               10683 non-null  float64
 24  Source_Chennai                                10683 non-null  float64
 25  Source_Delhi                                  10683 non-null  float64
 26  Source_Kolkata                                10683 non-null  float64
 27  Source_Mumbai                                 10683 non-null  float64
 28  Destination_Banglore                          10683 non-null  float64
 29  Destination_Cochin                            10683 non-null  float64
 30  Destination_Delhi                             10683 non-null  float64
 31  Destination_Hyderabad                         10683 non-null  float64
 32  Destination_Kolkata                           10683 non-null  float64
 33  Destination_New Delhi                         10683 non-null  float64
 34  Additional_Info_1 Long layover                10683 non-null  float64
 35  Additional_Info_1 Short layover               10683 non-null  float64
 36  Additional_Info_2 Long layover                10683 non-null  float64
 37  Additional_Info_Business class                10683 non-null  float64
 38  Additional_Info_Change airports               10683 non-null  float64
 39  Additional_Info_In-flight meal not included   10683 non-null  float64
 40  Additional_Info_No Info                       10683 non-null  float64
 41  Additional_Info_No check-in baggage included  10683 non-null  float64
 42  Additional_Info_No info                       10683 non-null  float64
 43  Additional_Info_Red-eye flight                10683 non-null  float64
dtypes: float64(34), int64(10)
memory usage: 3.6 MB